### ISSUE TITLE
NullPointerException When placed inside Fragment !!!

### ISSUE THREAD

**Issue by NammariMarkavip** [Lesilva/BetterSpinner#15]
```
  java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Filter.filter(java.lang.CharSequence, android.widget.Filter$FilterListener)' on a null object reference
            at android.widget.AutoCompleteTextView.performFiltering(AutoCompleteTextView.java:871)
            at com.weiwangcn.betterspinner.library.material.MaterialBetterSpinner.onFocusChanged(MaterialBetterSpinner.java:49)
            at android.view.View.handleFocusGainInternal(View.java:5347)
            at android.view.View.requestFocusNoSearch(View.java:8080)
            at android.view.View.requestFocus(View.java:8059)
            at android.view.View.requestFocus(View.java:8026)
            at android.view.View.requestFocus(View.java:8005)
            at com.weiwangcn.betterspinner.library.material.MaterialBetterSpinner.onTouchEvent(MaterialBetterSpinner.java:74)
            at android.view.View.dispatchTouchEvent(View.java:8920)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2684)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2400)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2684)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2400)
            at android.widget.ScrollView.dispatchTouchEvent(ScrollView.java:610)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2684)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2400)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2684)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2400)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2684)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2400)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2684)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2400)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2684)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2400)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2552)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1767)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2840)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2513)
            at android.view.View.dispatchPointerEvent(View.java:9125)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4632)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4470)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4020)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4073)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4039)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4153)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4047)
            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4210)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4020)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4073)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4039)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4047)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4020)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6480)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6379)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6350)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6570)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:143)
            at android.os.Looper

```

**Comment by Lesilva** [comment]
Post your code, this is not helpful.

**Comment by fmendoza** [comment]
happened to me as well, in my case, i forgot to call setAdapter() in the spinner.

**Comment by z1295802** [comment]
happen to me too, my code is as follow:

context = getActivity();
BetterSpinner spinner;
ArrayAdapter<String> areaList = new ArrayAdapter<String>(context, R.layout.spinner_item, area);
spinner = (BetterSpinner)rootView.findViewById(R.id.area_spinner);
spinner.setAdapter(areaList);
spinner.setOnItemSelectedListener(this);

and I just can figure out which line make this error, 

this.performFiltering("", 0);

is called when onFocusChanged method is called in plugin, 
so I go back to check onItemSelected in my code:

@Override
    public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
        this.selected = area[position];
    }

anyone have any idea?

**Comment by vasiledoe** [comment]
@z1295802  it would be better to provide some code about your solution ;)

**Comment by sherifrabee** [comment]
Disable focus of your spinner by adding this line in XML file: android:focusableInTouchMode="false"
