### ISSUE TITLE
app will crash if the betterSpinner did not setAdapter...

### ISSUE THREAD

**Issue by ynhenggg** [Lesilva/BetterSpinner#53]
dear Lesilva ,
the framwork is easy to use ,and it looks beautiful ....
but if it did not setAdapter ,the app crash..
someTimes we need to get data from the website ,
so ... will you update it ??

**Comment by Lesilva** [comment]
@ynhenggg do you have the crash log? And a quick way to fix it is to feed it a empty adapter then update it whenever you have data ready

**Comment by ynheng** [comment]
@Lesilva 
Dear Lesilva,
   I did it this way for now ,thanks for your reply , I will close the  @issue.

**Comment by ynheng** [comment]
Dear  @Lesilva,
I did it by the way you said ,but when I update it , it has no change ,I do not why...
(I am sure that the dataList is not empty)

```
                dataProvince = provinceBeanBaseBean.getList();
                listProvince.clear();
                for (ProvinceBean provinceBean : dataProvince) {
                    listProvince.add(provinceBean.getName());
                }
                toast(listProvince.toString());
                adapterProvince.notifyDataSetChanged();
```

**Comment by MerveGencer** [comment]
I have the same issue for version 1.1.0. If I did not set the adapter yet and user clicks it, better spinner crashes. I have to enable(false) if adapter is not set and enable(true) after I set the adapter for a quick workaround.

Here is the crashlog if you still want to see:

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Filter.filter(java.lang.CharSequence, android.widget.Filter$FilterListener)' on a null object reference
                                                                    at android.widget.AutoCompleteTextView.performFiltering(AutoCompleteTextView.java:862)
                                                                    at com.weiwangcn.betterspinner.library.material.MaterialBetterSpinner.onFocusChanged(MaterialBetterSpinner.java:49)
                                                                    at android.view.View.handleFocusGainInternal(View.java:5475)
                                                                    at android.view.View.requestFocusNoSearch(View.java:8473)
                                                                    at android.view.View.requestFocus(View.java:8452)
                                                                    at android.view.View.requestFocus(View.java:8419)
                                                                    at android.view.View.requestFocus(View.java:8398)
                                                                    at com.weiwangcn.betterspinner.library.material.MaterialBetterSpinner.onTouchEvent(MaterialBetterSpinner.java:74)
                                                                    at android.view.View.dispatchTouchEvent(View.java:9297)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2445)
                                                                    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent_aroundBody0(PhoneWindow.java:1756)
                                                                    at com.android.internal.policy.PhoneWindow$AjcClosure1.run(PhoneWindow.java:1)
                                                                    at android.view.PhoneWindowAO.ajc$around$android_view_PhoneWindowAO$2$99ce526bproceed(PhoneWindowAO.aj:113)
                                                                    at android.view.PhoneWindowAO.ajc$around$android_view_PhoneWindowAO$2$99ce526b(PhoneWindowAO.aj:117)
                                                                    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1756)
                                                                    at android.app.Activity.dispatchTouchEvent(Activity.java:2800)
                                                                    at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                    at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                    at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2406)
                                                                    at android.view.View.dispatchPointerEvent(View.java:9517)
                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4309)
                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4175)
                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3682)
                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3735)
                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3701)
                                                                    at a

**Comment by malkes** [comment]
I had the same issue too.

**Comment by dazza5000** [comment]
Did anyone find out a solution for this?

**Comment by malkes** [comment]
@dazza5000 I created a class that extends from BetterSpinner and overrode the method performFiltering and surrounded it with a try/catch. Ugly, but fast. Unfortunately, the object that throws the exception is private, if it were public a simple null check will fix the error.

**Comment by Emeritus-DarranKelinske** [comment]
My solution was more ugly. I put the thing in a scrollview and then had the scrollview as for focus before descendants...or something like that. It's ugly, but works.

Thank you!

**Comment by pcg92** [comment]
Thanks @malkes

**Comment by onuryurtturk** [comment]
same error. any solution?

**Comment by gpt3ch** [comment]
@malkes  can you post your code pls?

**Comment by asif1261** [comment]
Getting android spinner NullPointerException when rotate the screen

Hi! guys I'm having trouble with a spiner throwing a nullPointerExpression when rotating the screen

Here is the logcat:
E/AndroidRuntime: FATAL EXCEPTION: main Process: com.example.ritecare, PID: 15345 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Filter.filter(java.lang.CharSequence, android.widget.Filter$FilterListener)' on a null object reference at android.widget.AutoCompleteTextView.performFiltering(AutoCompleteTextView.java:1026) at com.weiwangcn.betterspinner.library.material.MaterialBetterSpinner.onFocusChanged(MaterialBetterSpinner.java:49) at android.view.View.handleFocusGainInternal(View.java:7478) at android.view.View.requestFocusNoSearch(View.java:12441) at android.view.View.requestFocus(View.java:12415) at android.view.View.requestFocus(View.java:12382) at android.view.View.requestFocus(View.java:12324) at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2166) at android.app.Activity.onRestoreInstanceState(Activity.java:1563) at android.app.Activity.performRestoreInstanceState(Activity.java:1518) at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1346) at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3310) at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221) at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201) at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) at android.os.Handler.dispatchMessage(Handler.java:107) at android.os.Looper.loop(Looper.java:214) at android.app.ActivityThread.main(ActivityThread.java:7356) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by asad-zaman** [comment]
Please check the solution here: 
https://stackoverflow.com/questions/58370824/android-material-spinner-nullpointerexception-on-autocompletetextview/58371922#58371922

**Comment by bilawalsharif23** [comment]
You have to give empty list or   add some string text like this("No patient list found")

List<String> NameList = new ArrayList<>();
        NameList.add("No patient list found");
        spinnerAdapter = new ArrayAdapter<String>(mContext, android.R.layout.simple_dropdown_item_1line, NameList);
        spinner.setAdapter(spinnerAdapter);

If you are going  to set adapter having empty or null arraylist spinner will crashes
