### ISSUE TITLE
BadTokenException when BetterSpinner used in popupWindow

### ISSUE THREAD

**Issue by BigHadron** [Lesilva/BetterSpinner#67]
Hey guys. I just wanted to set up the BetterSpinner in a PopupWindow in the ViewHolder of an Adapter from a RecyclerView. In my MainActivity it did work perfectly well to implement the betterSpinner similar to how I tried to do here. Maybe someone was facing the same problem or knows how to solve it. Thanks anyways.

Code where I implement the BetterSpinner:
`mStatusSpinner = (MaterialBetterSpinner) popupWindow.getContentView().findViewById(R.id.shortBetterSpinner);
                    String[] status = view.getResources().getStringArray(R.array.shortSpinnerContent);
                    ArrayAdapter adapter = new ArrayAdapter(popupWindow.getContentView().getContext(), android.R.layout.simple_dropdown_item_1line, status);
                    mStatusSpinner.setAdapter(adapter);`

XML file of my BetterSpinner:
`<com.weiwangcn.betterspinner.library.material.MaterialBetterSpinner
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="0.75"
            android:id="@+id/shortBetterSpinner"
            android:text="auswaehlen" />`

Exception stack trace:
`android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@61481e1 is not valid; is your activity running?
                                                                                at android.view.ViewRootImpl.setView(ViewRootImpl.java:678)
                                                                                at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
                                                                                at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                                at android.widget.PopupWindow.invokePopup(PopupWindow.java:1380)
                                                                                at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1236)
                                                                                at android.widget.ListPopupWindow.show(ListPopupWindow.java:671)
                                                                                at android.widget.AutoCompleteTextView.showDropDown(AutoCompleteTextView.java:1215)
                                                                                at com.weiwangcn.betterspinner.library.material.MaterialBetterSpinner.onTouchEvent(MaterialBetterSpinner.java:75)
                                                                                at android.view.View.dispatchTouchEvent(View.java:9939)`

Thanks.

**Comment by Marshall11** [comment]
Hey BigHadron, I got the exacte same problem with my PopupWindow. It would be nice if someone could help us! Have you found any other way to handle it?

**Comment by BigHadron** [comment]
Hey Marshall11, unfortunately I haven't found a workaround yet, I just went back to using the regular Spinner in this case. Neither a perfect nor a satisfying solution but the only one I found.
